### ISSUE TITLE
Add Layout File

### ISSUE THREAD

**Issue by Arianna-Salvini** [Arianna-Salvini/gitflow#1]
Add:

-  a new file app.blade.php in resourse/views/layouts
- a yield for page title 
- a yield for page content
- create partial for header
- create partial for footer

**Comment by Giovanni-Cattaneo** [comment]
i'll do this task, giovanni

**Comment by Arianna-Salvini** [comment]
There'r an error, you didn't create a branch

Please make the necessary changes and push again

**Comment by Giovanni-Cattaneo** [comment]
@Arianna-Salvini sorry for the mistake, ill fix it asap
